### PR TITLE
Adding Update Contact Function

### PR DESCRIPTION
**Pull request by rNLKJA**
- [x]  Does the code work?
- [x]  Are functions, methods, and variables adequately named?
- [ ]  Any test on the new component?
- [ ]  Is it well tested? All components could be rendered and pass the test.
- [x]  Is the code clear and easy to understand?
- [x]  Does it meet the team guidelines and style guides?
- [x]  Is there any duplicated code?
- [x]  Is documentation on functions, methods, classes, contexts, and behaviours adequate?
- [x]  Is the code as modular as possible?
- [x]  Are there better or simpler solutions?
- [x]  Is there any performance issue?

### CODE REVIEW

**Comment by rNLKJA** [comment]
# THIS FUNCTION IS NOT COMPLETED YET, DO NOT MERGE THE BRANCH

Please DO NOT merge this branch or close this pull request, but you still can add comment!

**Comment by rNLKJA** [comment]
TODO：Need move API in Contact itself to obain update

**Comment by rNLKJA** [comment]
Merged current working branch for Record DEBUGGING

**Comment by EcZww** [comment]
> Merged current working branch for Record DEBUGGING

bugs for creating record has been fixed. commit: 98dd618 at Branch "Front-End-dev"

**Pull request merged**
